version: '3.8'

services:
  nginxproxy:
    image: viziblyproxy
    restart: unless-stopped
    build:
      context: nginx
    ports:
      - "8080:80"
      - "10443:443"
    networks:
      - nginxproxy
      - vizibly
    volumes:
      - ./secrets/cert_key:/etc/ssl/cert_key/:ro
  vizibly:
    image: ghcr.io/whiskeycharlie/overfitting-viz:master
    restart: unless-stopped
    build:
      context: .
    networks:
      - vizibly

networks:
  nginxproxy:
  vizibly:
